# ----------------------------------------
# Created on: Tue May 14 18:52:29 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/pdsproject/project/project1/AorB/pango_sim_libraries/usim"
vmap  adc "D:/pdsproject/project/project1/AorB/pango_sim_libraries/adc"
vmap  ddrc "D:/pdsproject/project/project1/AorB/pango_sim_libraries/ddrc"
vmap  ddrphy "D:/pdsproject/project/project1/AorB/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "D:/pdsproject/project/project1/AorB/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "D:/pdsproject/project/project1/AorB/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "D:/pdsproject/project/project1/AorB/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "D:/pdsproject/project/project1/AorB/pango_sim_libraries/pciegen2"
vlog -work work   \
"D:/pdsproject/project/project1/AorB/source/AorB.v" \
"D:/pdsproject/project/project1/AorB/source/gate74LS00.v" \
"D:/pdsproject/project/project1/AorB/source/AorB_tb.v" 

# ----------------------------------------
