#Generated by Fabric Compiler ( version 2022.2-SP1-Lite <build 132640> ) at Wed Jun 12 16:51:26 2024

add_design "D:/pdsproject/project/project1/AorB/test2/test2_1/D/source/gate74LS74.v"
add_design "D:/pdsproject/project/project1/AorB/test2/test2_1/D/source/D1.v"
