
//
// Generated by Fabric Compiler (version 2022.2-SP1-Lite<build 132640>) at Tue May 14 18:46:18 2024
//
module AorB
(
    F,
    A,
    B
);

(* PAP_IO_DIRECTION="INPUT", PAP_IO_LOC="H14", PAP_IO_VCCIO="1.2", PAP_IO_STANDARD="LVCMOS12", PAP_IO_NONE="TRUE", PAP_PORT_BUF_UNIT_TYPE="GTP_INBUF" *)    input A;
(* PAP_IO_DIRECTION="INPUT", PAP_IO_LOC="G13", PAP_IO_VCCIO="1.2", PAP_IO_STANDARD="LVCMOS12", PAP_IO_NONE="TRUE", PAP_PORT_BUF_UNIT_TYPE="GTP_INBUF" *)    input B;
(* PAP_IO_DIRECTION="OUTPUT", PAP_IO_LOC="N15", PAP_IO_VCCIO="1.2", PAP_IO_STANDARD="LVCMOS12", PAP_IO_DRIVE="2", PAP_IO_NONE="TRUE", PAP_IO_SLEW="SLOW", PAP_PORT_BUF_UNIT_TYPE="GTP_OUTBUF" *)    output F;

    wire \A_ibuf/ntD ;
    wire \B_ibuf/ntD ;
    wire \F_obuf/ntO ;
    wire \IOL_151_134/MIPI_OUT/_N1 ;
    wire \IOL_151_134/MIPI_OUT/_N3 ;
    wire \U1/N4_inv_rnmt ;
    wire nt_A;
    wire nt_B;

    V_LUT5 /* U1/N4/gateop_perm/FYA/FY */ #(
            .INIT(32'b11111111111111111111111100000000))
        \CLMA_146_225/FYA/FY  (
            .Y (\U1/N4_inv_rnmt ),
            .I0 (),
            .I1 (),
            .I2 (),
            .I3 (nt_B),
            .I4 (nt_A));
	// LUT = (I4)|(I3) ;

    V_GRS GRS_INST (
            .GRS_N (1'b1));

    V_OBUF /* F_obuf/opit_0/obuf */ #(
            .IOSTANDARD("LVCMOS12"), 
            .SLEW_RATE("SLOW"), 
            .DRIVE_STRENGTH("8"))
        \IOBD_152_134/obuf  (
            .O (F),
            .I (\F_obuf/ntO ));
	// ../source/AorB.v:3

    V_IBUF /* A_ibuf/opit_0/ibuf */ #(
            .IOSTANDARD("LVCMOS12"), 
            .TERM_DDR("ON"))
        \IOBD_152_226/ibuf  (
            .O (\A_ibuf/ntD ),
            .I (A));
	// ../source/AorB.v:2

    V_IBUF /* B_ibuf/opit_0/ibuf */ #(
            .IOSTANDARD("LVCMOS12"), 
            .TERM_DDR("ON"))
        \IOBS_152_233/ibuf  (
            .O (\B_ibuf/ntD ),
            .I (B));
	// ../source/AorB.v:2

    V_MUX2 \IOL_151_134/MIPI_OUT/V_MUX2  (
            .Z (\IOL_151_134/MIPI_OUT/_N3 ),
            .I0 (\IOL_151_134/MIPI_OUT/_N1 ),
            .I1 (),
            .SEL (1'b0));
	// ../source/AorB.v:3

    V_BUF \IOL_151_134/OUTPUT_DATA_MUX/V_BUF  (
            .Z (\IOL_151_134/MIPI_OUT/_N1 ),
            .I (\U1/N4_inv_rnmt ));
	// ../source/AorB.v:3

    V_BUF \IOL_151_134/OUT_DELSEL_MUX/V_BUF  (
            .Z (\F_obuf/ntO ),
            .I (\IOL_151_134/MIPI_OUT/_N3 ));
	// ../source/AorB.v:3

    V_BUF \IOL_151_226/IN_DELSEL_MUX/V_BUF  (
            .Z (nt_A),
            .I (\A_ibuf/ntD ));
	// ../source/AorB.v:2

    V_BUF \IOL_151_233/IN_DELSEL_MUX/V_BUF  (
            .Z (nt_B),
            .I (\B_ibuf/ntD ));
	// ../source/AorB.v:2


endmodule

